/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { BadgeProps, CheckboxFieldProps, FlexProps, IconProps, ImageProps, StepperFieldProps, TextFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type NftMyPageOverridesProps = {
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    NftMyPage?: PrimitiveOverrideProps<ViewProps>;
    "nft (1) 338403087"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 121"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 100"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 27"?: PrimitiveOverrideProps<FlexProps>;
    ZIR?: PrimitiveOverrideProps<TextProps>;
    Sanha38?: PrimitiveOverrideProps<TextProps>;
    "Frame 30"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338403095"?: PrimitiveOverrideProps<ImageProps>;
    sanha38?: PrimitiveOverrideProps<TextProps>;
    "Frame 122"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 106"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10538403099"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138403100"?: PrimitiveOverrideProps<FlexProps>;
    "Collection of"?: PrimitiveOverrideProps<TextProps>;
    "Frame 102"?: PrimitiveOverrideProps<FlexProps>;
    "Owned by"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10338403105"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10438403107"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 6"?: PrimitiveOverrideProps<ImageProps>;
    "ghrgclzzd 7"?: PrimitiveOverrideProps<ImageProps>;
    "ghrgclzzd 8"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 10338403111"?: PrimitiveOverrideProps<FlexProps>;
    "Floor Price"?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38403113"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10438403114"?: PrimitiveOverrideProps<FlexProps>;
    "Total Sales"?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38403116"?: PrimitiveOverrideProps<TextProps>;
    "Group 4"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 7"?: PrimitiveOverrideProps<IconProps>;
    "..."?: PrimitiveOverrideProps<TextProps>;
    "Frame 123"?: PrimitiveOverrideProps<FlexProps>;
    "My Page"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 16"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 156"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 153"?: PrimitiveOverrideProps<FlexProps>;
    CheckboxField38403547?: PrimitiveOverrideProps<CheckboxFieldProps>;
    "Frame 11838403144"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 338403145"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11638403146"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11538403147"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138403148"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338403149"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3838403150"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10538403151"?: PrimitiveOverrideProps<FlexProps>;
    Reserve38403152?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38403153"?: PrimitiveOverrideProps<TextProps>;
    "Frame 15238403546"?: PrimitiveOverrideProps<FlexProps>;
    StepperField38403396?: PrimitiveOverrideProps<StepperFieldProps>;
    TextField38403509?: PrimitiveOverrideProps<TextFieldProps>;
    Badge38403247?: PrimitiveOverrideProps<BadgeProps>;
    "Frame 155"?: PrimitiveOverrideProps<FlexProps>;
    CheckboxField38403611?: PrimitiveOverrideProps<CheckboxFieldProps>;
    "Frame 11838403612"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 338403613"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11638403614"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11538403615"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138403616"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338403617"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3838403618"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10538403619"?: PrimitiveOverrideProps<FlexProps>;
    Reserve38403620?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38403621"?: PrimitiveOverrideProps<TextProps>;
    "Frame 15238403622"?: PrimitiveOverrideProps<FlexProps>;
    StepperField38403623?: PrimitiveOverrideProps<StepperFieldProps>;
    TextField38403624?: PrimitiveOverrideProps<TextFieldProps>;
    Badge38403625?: PrimitiveOverrideProps<BadgeProps>;
    "Frame 154"?: PrimitiveOverrideProps<FlexProps>;
    CheckboxField38403565?: PrimitiveOverrideProps<CheckboxFieldProps>;
    "Frame 11838403566"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 338403567"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11638403568"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11538403569"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138403570"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338403571"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3838403572"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10538403573"?: PrimitiveOverrideProps<FlexProps>;
    Reserve38403574?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38403575"?: PrimitiveOverrideProps<TextProps>;
    "Frame 15238403576"?: PrimitiveOverrideProps<FlexProps>;
    StepperField38403577?: PrimitiveOverrideProps<StepperFieldProps>;
    TextField38403578?: PrimitiveOverrideProps<TextFieldProps>;
    Badge38403579?: PrimitiveOverrideProps<BadgeProps>;
} & EscapeHatchProps;
export declare type NftMyPageProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: NftMyPageOverridesProps | undefined | null;
}>;
export default function NftMyPage(props: NftMyPageProps): React.ReactElement;
