/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type NftUserinfoOverridesProps = {
    "3"?: PrimitiveOverrideProps<TextProps>;
    "4"?: PrimitiveOverrideProps<TextProps>;
    NftUserinfo?: PrimitiveOverrideProps<ViewProps>;
    "nft (1) 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 99"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 100"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 27"?: PrimitiveOverrideProps<FlexProps>;
    ZIR?: PrimitiveOverrideProps<TextProps>;
    Sanha38?: PrimitiveOverrideProps<TextProps>;
    "Frame 30"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 337962824"?: PrimitiveOverrideProps<ImageProps>;
    sanha38?: PrimitiveOverrideProps<TextProps>;
    "Frame 107"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 106"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10537962861"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10137962831"?: PrimitiveOverrideProps<FlexProps>;
    "Collection of"?: PrimitiveOverrideProps<TextProps>;
    "Frame 102"?: PrimitiveOverrideProps<FlexProps>;
    "Owned by"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10337962839"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10437962845"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 6"?: PrimitiveOverrideProps<ImageProps>;
    "ghrgclzzd 7"?: PrimitiveOverrideProps<ImageProps>;
    "ghrgclzzd 8"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 10337962854"?: PrimitiveOverrideProps<FlexProps>;
    "Floor Price"?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH37962856"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10437962857"?: PrimitiveOverrideProps<FlexProps>;
    "Total Sales"?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH37962859"?: PrimitiveOverrideProps<TextProps>;
    "Group 4"?: PrimitiveOverrideProps<FlexProps>;
    "Ellipse 7"?: PrimitiveOverrideProps<IconProps>;
    "..."?: PrimitiveOverrideProps<TextProps>;
    "Frame 108"?: PrimitiveOverrideProps<FlexProps>;
    NFTs?: PrimitiveOverrideProps<TextProps>;
    Description?: PrimitiveOverrideProps<TextProps>;
    Activity?: PrimitiveOverrideProps<TextProps>;
    "Frame 114"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 113"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 109"?: PrimitiveOverrideProps<FlexProps>;
    "Live Action"?: PrimitiveOverrideProps<TextProps>;
    "Frame 537972822"?: PrimitiveOverrideProps<FlexProps>;
    "037972817"?: PrimitiveOverrideProps<TextProps>;
    "Frame 110"?: PrimitiveOverrideProps<FlexProps>;
    "Buy Now"?: PrimitiveOverrideProps<TextProps>;
    "Frame 537972827"?: PrimitiveOverrideProps<FlexProps>;
    "037972828"?: PrimitiveOverrideProps<TextProps>;
    "Frame 111"?: PrimitiveOverrideProps<FlexProps>;
    "Reserve Price"?: PrimitiveOverrideProps<TextProps>;
    "Frame 537972831"?: PrimitiveOverrideProps<FlexProps>;
    "037972832"?: PrimitiveOverrideProps<TextProps>;
    "Frame 112"?: PrimitiveOverrideProps<FlexProps>;
    "Most Active"?: PrimitiveOverrideProps<TextProps>;
    "Frame 537972835"?: PrimitiveOverrideProps<FlexProps>;
    "down 2"?: PrimitiveOverrideProps<ViewProps>;
    Vector?: PrimitiveOverrideProps<IconProps>;
    "Frame 12037972999"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 118"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 337972949"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11637972950"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11537972951"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10137972952"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 337972953"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3837972954"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10537972955"?: PrimitiveOverrideProps<FlexProps>;
    Reserve37972956?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH37972957"?: PrimitiveOverrideProps<TextProps>;
    "Frame 119"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 338082819"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11638082820"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11538082821"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138082822"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338082823"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3838082824"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10538082825"?: PrimitiveOverrideProps<FlexProps>;
    Reserve38082826?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38082827"?: PrimitiveOverrideProps<TextProps>;
    "Frame 12038082828"?: PrimitiveOverrideProps<FlexProps>;
    "nft (1) 338082829"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 11638082830"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 11538082831"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 10138082832"?: PrimitiveOverrideProps<FlexProps>;
    "ghrgclzzd 338082833"?: PrimitiveOverrideProps<ImageProps>;
    "@sanha3838082834"?: PrimitiveOverrideProps<TextProps>;
    "Frame 10538082835"?: PrimitiveOverrideProps<FlexProps>;
    Reserve38082836?: PrimitiveOverrideProps<TextProps>;
    "1.30 ETH38082837"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 15"?: PrimitiveOverrideProps<ViewProps>;
} & EscapeHatchProps;
export declare type NftUserinfoProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: NftUserinfoOverridesProps | undefined | null;
}>;
export default function NftUserinfo(props: NftUserinfoProps): React.ReactElement;
